# Generated by Django 2.2.20 on 2021-04-19 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="w16data1",
            options={"managed": False, "ordering": ["pk", "id_ozono_aggregazione"]},
        ),
    ]
