# Generated by Django 2.2.20 on 2021-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20210419_1226"),
    ]

    operations = [
        migrations.CreateModel(
            name="QaMisure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_venue", models.IntegerField()),
                ("data_emissione", models.DateTimeField()),
                ("data_scadenza", models.DateTimeField()),
                ("id_scadenza", models.IntegerField(blank=True, null=True)),
                ("id_strumentazione", models.SmallIntegerField()),
                ("id_qa_aggregazione", models.SmallIntegerField()),
                ("id_qa_parametro", models.CharField(max_length=10)),
                (
                    "valore_originale_num",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "valore_validato_num",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("valore_originale_classe", models.IntegerField(blank=True, null=True)),
                ("valore_validato_classe", models.IntegerField(blank=True, null=True)),
                ("valore_originale_txt", models.TextField(blank=True, null=True)),
                ("valore_validato_txt", models.TextField(blank=True, null=True)),
                ("last_update", models.DateTimeField()),
                ("username", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "qa_misure",
                "managed": False,
            },
        ),
    ]
