# Generated by Django 2.2.20 on 2021-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_qamisure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkyConditionClasses",
            fields=[
                (
                    "id_classes_value",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("ordinamento", models.IntegerField()),
            ],
            options={
                "db_table": "sky_condition_classes",
                "managed": False,
            },
        ),
    ]
