# Generated by Django 3.2.5 on 2021-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_skyconditionclasses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="w05classes",
            options={"managed": False, "ordering": ["id_classes"]},
        ),
    ]
