# Generated by Django 3.2.8 on 2021-10-25 14:09

from django.db import migrations, models
import django.db.models.deletion


def populate_bulletins(apps, schema_editor):
    BulletinsModel = apps.get_model("core", "bulletins")
    BulletinsModel.objects.get_or_create(prodotto="meteo", tabella="w05")
    BulletinsModel.objects.get_or_create(prodotto="ozono", tabella="w16")
    BulletinsModel.objects.get_or_create(prodotto="slops", tabella="w29")
    BulletinsModel.objects.get_or_create(prodotto="piene", tabella="w22")
    BulletinsModel.objects.get_or_create(
        prodotto="verificapiene", tabella="w22verifica"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210814_0737"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bulletins",
            fields=[
                ("prodotto", models.TextField(primary_key=True, serialize=False)),
                ("tabella", models.TextField(null=True)),
                ("auto", models.BooleanField(default=False)),
                ("time", models.TimeField(default="12:30")),
            ],
            options={
                "db_table": "bollettini",
                "managed": True,
            },
        ),
        migrations.RunPython(populate_bulletins),
        migrations.AlterField(
            model_name="Bulletins", name="tabella", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="Destinazioni",
            name="prodotto",
            field=models.ForeignKey(
                db_column="prodotto",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.bulletins",
            ),
        ),
    ]
