# Generated by Django 3.2.8 on 2021-10-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20211025_1409"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulletins",
            options={"managed": True, "verbose_name_plural": "Bulletins"},
        ),
        migrations.AlterModelOptions(
            name="destinazioni",
            options={"managed": True, "verbose_name_plural": "Destinazioni"},
        ),
    ]
