# Generated by Django 3.2.9 on 2021-11-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20211025_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletins",
            name="tabella",
            field=models.TextField(null=True),
        ),
    ]
