#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 manage.py collectstatic --no-input
python3 manage.py migrate
exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'
