--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3 (Debian 15.3-1.pgdg120+1)
-- Dumped by pg_dump version 15.3 (Debian 15.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: w30; Type: TABLE; Schema: public; Owner: weboll
--

CREATE TABLE public.w30 (
    id_w30 integer NOT NULL,
    seq_num bigint,
    data_emissione timestamp with time zone NOT NULL,
    data_prossimo_aggiornamento timestamp with time zone NOT NULL,
    status character varying(1) NOT NULL,
    last_update timestamp with time zone NOT NULL,
    username character varying(30) NOT NULL,
    id_w30_parent integer,
    firstguess text NOT NULL
);


ALTER TABLE public.w30 OWNER TO weboll;

--
-- Name: w30_id_w30_seq; Type: SEQUENCE; Schema: public; Owner: weboll
--

ALTER TABLE public.w30 ALTER COLUMN id_w30 ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.w30_id_w30_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: w30 w30_pkey; Type: CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30
    ADD CONSTRAINT w30_pkey PRIMARY KEY (id_w30);


--
-- PostgreSQL database dump complete
--

