--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3 (Debian 15.3-1.pgdg120+1)
-- Dumped by pg_dump version 15.3 (Debian 15.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: w30_data; Type: TABLE; Schema: public; Owner: weboll
--

CREATE TABLE public.w30_data (
    id_w30_data integer NOT NULL,
    numeric_value integer,
    id_aggregazione integer NOT NULL,
    id_allertamento character varying(6) NOT NULL,
    id_parametro character varying(15) NOT NULL,
    id_time_layouts integer NOT NULL,
    id_w30 integer NOT NULL
);


ALTER TABLE public.w30_data OWNER TO weboll;

--
-- Name: w30_data_id_w30_data_seq; Type: SEQUENCE; Schema: public; Owner: weboll
--

ALTER TABLE public.w30_data ALTER COLUMN id_w30_data ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.w30_data_id_w30_data_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: w30_data w30_data_pkey; Type: CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_pkey PRIMARY KEY (id_w30_data);


--
-- Name: w30_data_id_aggregazione_376fc44d; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_aggregazione_376fc44d ON public.w30_data USING btree (id_aggregazione);


--
-- Name: w30_data_id_allertamento_bc3f5233; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_allertamento_bc3f5233 ON public.w30_data USING btree (id_allertamento);


--
-- Name: w30_data_id_allertamento_bc3f5233_like; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_allertamento_bc3f5233_like ON public.w30_data USING btree (id_allertamento varchar_pattern_ops);


--
-- Name: w30_data_id_parametro_58631ff5; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_parametro_58631ff5 ON public.w30_data USING btree (id_parametro);


--
-- Name: w30_data_id_parametro_58631ff5_like; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_parametro_58631ff5_like ON public.w30_data USING btree (id_parametro varchar_pattern_ops);


--
-- Name: w30_data_id_time_layouts_12d6ac23; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_time_layouts_12d6ac23 ON public.w30_data USING btree (id_time_layouts);


--
-- Name: w30_data_id_w30_578a2dea; Type: INDEX; Schema: public; Owner: weboll
--

CREATE INDEX w30_data_id_w30_578a2dea ON public.w30_data USING btree (id_w30);


--
-- Name: w30_data w30_data_id_aggregazione_376fc44d_fk_aggregazi; Type: FK CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_id_aggregazione_376fc44d_fk_aggregazi FOREIGN KEY (id_aggregazione) REFERENCES public.aggregazione(id_aggregazione) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: w30_data w30_data_id_allertamento_bc3f5233_fk_aree_alle; Type: FK CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_id_allertamento_bc3f5233_fk_aree_alle FOREIGN KEY (id_allertamento) REFERENCES public.aree_allertamento(id_allertamento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: w30_data w30_data_id_parametro_58631ff5_fk_parametro_id_parametro; Type: FK CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_id_parametro_58631ff5_fk_parametro_id_parametro FOREIGN KEY (id_parametro) REFERENCES public.parametro(id_parametro) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: w30_data w30_data_id_time_layouts_12d6ac23_fk_time_layo; Type: FK CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_id_time_layouts_12d6ac23_fk_time_layo FOREIGN KEY (id_time_layouts) REFERENCES public.time_layouts(id_time_layouts) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: w30_data w30_data_id_w30_578a2dea_fk_w30_id_w30; Type: FK CONSTRAINT; Schema: public; Owner: weboll
--

ALTER TABLE ONLY public.w30_data
    ADD CONSTRAINT w30_data_id_w30_578a2dea_fk_w30_id_w30 FOREIGN KEY (id_w30) REFERENCES public.w30(id_w30) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

