--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3 (Debian 15.3-1.pgdg120+1)
-- Dumped by pg_dump version 15.3 (Debian 15.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: w34; Type: TABLE; Schema: public; Owner: weboll
--

CREATE TABLE public.w34 (
    id_w34 integer NOT NULL,
    seq_num bigint,
    data_emissione timestamp with time zone NOT NULL,
    status character varying(1) NOT NULL,
    last_update timestamp with time zone NOT NULL,
    username character varying(30) NOT NULL
);

ALTER TABLE public.w34 OWNER TO weboll;

ALTER TABLE public.w34 ALTER COLUMN id_w34 ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.w34_id_w34_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.w34
    ADD CONSTRAINT w34_pkey PRIMARY KEY (id_w34);


--
-- Name: w34_data; Type: TABLE; Schema: public; Owner: weboll
--

CREATE TABLE public.w34_data (
    id_w34_data integer NOT NULL,
    numeric_value integer,
    id_aggregazione integer NOT NULL,
    id_venue character varying(6) NOT NULL,
    id_parametro character varying(15) NOT NULL,
    id_time_layouts integer NOT NULL,
    id_w34 integer NOT NULL
);

ALTER TABLE public.w34_data OWNER TO weboll;

ALTER TABLE public.w34_data ALTER COLUMN id_w34_data ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.w34_data_id_w34_data_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.w34_data
    ADD CONSTRAINT w34_data_pkey PRIMARY KEY (id_w34_data);

CREATE INDEX w34_data_id_aggregazione_376fc44d ON public.w34_data USING btree (id_aggregazione);

CREATE INDEX w34_data_id_venue_bc3f5233 ON public.w34_data USING btree (id_venue);

CREATE INDEX w34_data_id_venue_bc3f5233_like ON public.w34_data USING btree (id_venue varchar_pattern_ops);

CREATE INDEX w34_data_id_parametro_58631ff5 ON public.w34_data USING btree (id_parametro);

CREATE INDEX w34_data_id_parametro_58631ff5_like ON public.w34_data USING btree (id_parametro varchar_pattern_ops);

CREATE INDEX w34_data_id_time_layouts_12d6ac23 ON public.w34_data USING btree (id_time_layouts);

CREATE INDEX w34_data_id_w34_578a2dea ON public.w34_data USING btree (id_w34);

ALTER TABLE ONLY public.w34_data
    ADD CONSTRAINT w34_data_id_aggregazione_376fc44d_fk_aggregazi FOREIGN KEY (id_aggregazione) REFERENCES public.aggregazione(id_aggregazione) DEFERRABLE INITIALLY DEFERRED;

-- ALTER TABLE ONLY public.w34_data
--     ADD CONSTRAINT w34_data_id_venue_bc3f5233_fk_venue FOREIGN KEY (id_venue) REFERENCES public.venue(id_venue) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.w34_data
    ADD CONSTRAINT w34_data_id_parametro_58631ff5_fk_parametro_id_parametro FOREIGN KEY (id_parametro) REFERENCES public.parametro(id_parametro) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.w34_data
    ADD CONSTRAINT w34_data_id_time_layouts_12d6ac23_fk_time_layo FOREIGN KEY (id_time_layouts) REFERENCES public.time_layouts(id_time_layouts) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.w34_data
    ADD CONSTRAINT w34_data_id_w34_578a2dea_fk_w34_id_w34 FOREIGN KEY (id_w34) REFERENCES public.w34(id_w34) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\c
\set command `echo "curl $DATA_LOCATION/w34_last_2_days.copy"`
COPY w34 FROM PROGRAM :'command' CSV HEADER DELIMITER ',' ;
\set command `echo "curl $DATA_LOCATION/w34_data_last_2_days.copy"`
COPY w34_data FROM PROGRAM :'command' CSV HEADER;


ALTER TABLE public.w34 ADD id_w34_parent INTEGER DEFAULT NULL;